var title0 = "<span class=\"header\">&emsp;Introduction</span><br><br>"

var chapter0 = "&emsp; In late October, 1996, a routine patrol in the skies over Death Valley spotted an abandoned mini-van in a remote area of the park.  The vehicle was soon found to have been rented months earlier by a German family, Egbert Rimkus (34) & his son, Georg Weber (11), Egbert's girlfriend Cornelia Meyer (28) & her son, Max Meyer (4).  The family was due to return to Germany nearly three months before their van was found, but they never boarded their flight.  The initial search of the area found little evidence of where the family may be.<br><br>&emsp; Over a decade later, a former search & rescue member, Tom Mahood, became interested in the case and thanks to his efforts and creative problem solving the mystery of the \"Death Valley Germans\" was finally solved.  Tom's in-depth write up covers the story of the search and is available at OtherHand.org.<br><br>&emsp; This webmap details the story of the German's final days, based on Tom Mahood's own theory of how the events may have taken place.  Use the controls below to walk through the events and locations involved with this tragedy."

var title1 = "<span class=\"header\">&emsp;Heading into the Park</span><br><br>"

var chapter1 = "&emsp; On July 22nd, the Germans stopped at the Furnace Creek Visitor Center, having left Las Vegas sometime earlier in the day. The lush green of the golf course standing in stark contrast to the landscape they spent the afternoon driving through.  Here they purchase a German language map then head south on Badwater Road, they turn off the pavement onto the relatively-high quality dirt of West Side Road and eventually onto the rough Hanaupah Canyon Rd. <br><br>&emsp; Photos found on the family's camera suggest they spent the night up in Hanaupah, likely in an attempt to escape the heat of the valley, where the high temperature reached 123 &#176;F that day."

var title2 = "<span class=\"header\">&emsp;(Very) Warm Springs Canyon</span><br><br>"

var chapter2 = "&emsp; On the morning of the 23rd, the family drove back down Hanaupah and continued south on the West Side Road.  The road was easily traversable in their mini-van and Egbert was probably feeling quite confident in his driving abilities after having successfully driven the much rougher Hanuapah Canyon road.  At some point Egbert and Cornelia likely discussed heading out of the park over Mengle Pass to the southwest in order to head towards Yosemite before returning to LA, where they were due to return their van on the 26th. <br><br>&emsp; As the Germans turned onto Warm Spring Canyon Road leaving the main valley, the temperature likely approached 125 &#176;F. As they approached Warm Springs Camp from the east, the road was likely in decent shape.  The family stopped at the camp, perhaps hoping to ask about road conditions further up, but the found the camp empty.  The family signed the log book, indicating their intentions to head over Mengle Pass, and continued to the west."

var title3 = "<span class=\"header\">&emsp;Trouble at Mengle Pass</span><br><br>"

var chapter3 = "&emsp; As the family continued westward, the road conditions would have began to deteriorate.  This may have been worrisome but entering the broad Butte Valley at nearly 4000 feet elevation, they would have once again found relatively good roads and the family may have been enjoying their afternoon in relatively comfortable temperatures roughly 20 &#176;F cooler than back in Badwater.<br><br>&emsp; A flag from the 'Geologist's Cabin' was found in the family's van, indicating they stopped in and would have been aware of the shelter and emergency food & water stores available at the cabin, which was just 4 miles west of where the van was ultimately deserted. <br><br>&emsp; The Germans continued to the southwest but as they approached Mengle Pass, it would have become painfully clear that their van was incapable of proceeding.  It was now late afternoon and their plan to reach Yosemite by that evening was in significant danger."

var title4 = "<span class=\"header\">&emsp;Wrong Turn or Wrong Map?</span><br><br>"

var chapter4 = "&emsp; Being forced to turn around, the family was likely not looking forward to the long, rough, drive back to Badwater Road.  Looking at their maps, they would have noticed a shortcut down Anvil Canyon.  Unfortunately, this road had been closed years prior but their German language maps had not been properly updated.  Whether the family made a conscious decision or simply took a wrong turn is unknown. Regardless, after turning around, the Germans took a right onto Anvil Canyon Road. <br><br>&emsp; The first section of the road until the head of the canyon was in reasonable condition.  As they reached Anvil Spring and entered the Canyon, the road would begin to transition into a now unmaintained wash.  Egbert would have had to keep up the vans speed to avoid getting stuck in the sand, likely driving too fast for the conditions.  Eventually rocks in the wash tore up the rear tires and one of the front tires.  The van became stuck in the loose sand 2 miles from where they left the maintained portion of the road."

var title5 = "<span class=\"header\">&emsp;Three Flat Tires, Three Ways Out</span><br><br>"

var chapter5 = "&emsp; The van was now undriveable.  It was late afternoon and they had likely not seen another vehicle all day.  The family wouldn't make it to Yosemite, so the focus likely turned on how to get out of this situation and make their flight home.  A large butt-print and empty beer bottle found in the afternoon shade of a bush 1.7 miles down the road suggest Egbert took a walk and sat down to think things over, possibly while Cornelia comforted the children back at the van. <br><br>&emsp; They could return to the Geologist's Cabin, knowing of it's shelter, but they likely worried nobody would arrive before missing their flight. From the 'bottle bush', Egbert could see down Anvil Canyon all the way to the Badwater Road, nearly 16 miles east.  This may have felt like a tempting option but the long distance and dangerous temperatures of the main valley were likely worrisome. Even if they made it, this portion of the road was seldom travelled in July. <br><br>&emsp; Looking at their map, Egbert may have noticed the northern border of the China Lake Naval Weapons Center just 9 miles to the south. Unfamiliar with the vastness of military installations in the desert southwest, he may have thought the installation would have patrolled borders.  This may have seemed like their best bet to find help in time to make their flight."

var title6 = "<span class=\"header\">&emsp;A Heartbreaking View</span><br><br>"

var chapter6 = "&emsp; The family likely spent the night at the van and set out on foot early on July 24th.  Heading east down Anvil Canyon and then south through one of the gaps in the hills, the high would have approached 105 &#176;F that afternoon. The terrain would be rough with little shade and no water. <br><br>&emsp; Reaching the far side of a broad alluvial fan, the only shade was a small bluff in view of a low pass to the south.  It's possible one of the adults rested here with the children while whoever had the most energy climbed to get a view to the south.  Upon reaching the small gap where they should have been able to look down into the China Lake installation to the south, they would have been heartbroken to see nothing but miles of desert.  They returned to the small bluff, exhausted and dehydrated.  This is where the remains of Cornelia & Egbert were eventually found. <br><br>&emsp; While no official statements have ever been made concerning the children, some evidence suggests that their remains were found nearby, perhaps to the northwest, back towards the van."

var title7 = "<span class=\"header\">&emsp;Credits & Dedications</span><br><br>"

var chapter7 = "&emsp; If you haven't read Tom Mahood's original account of this story, I once again suggest you visit his website OtherHand.org. A static version of this story is also available at my personal website nicholasrolstad.com <br><br><br>&emsp; Dedicated to the memory of Egbert, Cornelia, George & Max.  May they rest in peace."
